from typing import Optional, List, Dict, Any, Union
from pydantic import BaseModel, Field, ConfigDict


class ClaimVerificationRequest(BaseModel):
    claim: str = Field(..., min_length=1, description="The specific factual claim or statement generated by LLM")
    source_chunk: Union[str, Dict[str, Any]] = Field(..., description="The cited source chunk text or chunk dictionary object")
    chunk_id: Optional[str] = Field(None, description="Optional chunk identifier")


class ClaimVerificationResult(BaseModel):
    claim: str = Field(..., description="The analyzed claim text")
    chunk_id: Optional[str] = Field(None, description="The cited source chunk ID")
    faithfulness_score: float = Field(..., ge=0.0, le=100.0, description="Faithfulness percentage score from 0.0 to 100.0%")
    is_faithful: bool = Field(..., description="True if faithfulness score meets or exceeds the reliability threshold (default 70%)")
    verdict: str = Field(..., description="Categorical verdict: 'SUPPORTED', 'PARTIALLY_SUPPORTED', or 'UNSUPPORTED'")
    unsupported_entities: List[str] = Field(default_factory=list, description="Key technical entities (endpoints, params) present in claim but absent from source chunk")
    semantic_similarity: float = Field(..., ge=0.0, le=1.0, description="Cosine semantic similarity between claim and chunk")
    token_overlap_score: float = Field(..., ge=0.0, le=1.0, description="Token and lexical overlap ratio")
    reasoning: str = Field(..., description="Explanation of the faithfulness evaluation")

    model_config = ConfigDict(from_attributes=True)


class AnswerFaithfulnessRequest(BaseModel):
    answer: str = Field(..., description="Full LLM generated answer containing [^chunk_id] tags")
    context_chunks: List[Dict[str, Any]] = Field(..., description="List of available context chunks")
    threshold: float = Field(70.0, ge=0.0, le=100.0, description="Pass threshold for claim faithfulness")


class AnswerFaithfulnessReport(BaseModel):
    overall_score: float = Field(..., ge=0.0, le=100.0, description="Weighted average faithfulness score (0-100%)")
    is_faithful: bool = Field(..., description="True if all claims meet threshold")
    total_claims: int = Field(0, description="Total individual claims parsed from answer")
    faithful_claims_count: int = Field(0, description="Number of claims evaluated as faithful")
    unfaithful_claims_count: int = Field(0, description="Number of claims evaluated as unfaithful/hallucinated")
    claim_verifications: List[ClaimVerificationResult] = Field(default_factory=list, description="Per-claim verification breakdown")

    model_config = ConfigDict(from_attributes=True)
